### ISSUE TITLE
可以集成到插件库使用吗

### ISSUE THREAD

**Issue by kirbystudy** [AniNet-Project/AniNet#19]

**Comment by Nanguage** [comment]
是说作为一个 JS 的库来使用吗？目前是不行的，没有作为一个库来开发

**Comment by kirbystudy** [comment]
好的谢谢，我目前有个需求就是用到你这种关系图，想集成到项目里使用的，我看了你源码里是用类组件，我用的是函数组件，方法里有些不同，可以指导一下在自己的项目里怎么引入吗。

**Comment by Nanguage** [comment]
类组件和函数组件应该是可以互相调用的。你可以把用到的代码粘贴过去，在你的项目里导入

**Comment by kirbystudy** [comment]
好的感谢

**Comment by kirbystudy** [comment]
对了，还有一件事，就是下载react-vis-network依赖的时候报错了，我react的版本是18以上，有没有办法可以兼容18版本。

**Comment by Nanguage** [comment]
不太清楚，好久没维护了这个项目。要不你到 react-vis-network 那里开个 issue

**Comment by kirbystudy** [comment]
这个估计作者都懒得维护了
